/home/120/av5889/.bashrc: line 52: spack/share/spack/setup-env.sh: No such file or directory
Loading jupyterlab/3.4.3-py3.9
  Loading requirement: intel-mkl/2020.3.304 python3/3.9.2
Process Process-1:
Process Process-2:
Process Process-3:
Process Process-4:
Process Process-5:
Process Process-6:
Process Process-7:
Process Process-8:
Process Process-9:
Process Process-10:
Process Process-11:
Process Process-12:
Process Process-13:
Process Process-14:
Process Process-15:
Process Process-16:
Process Process-18:
Process Process-17:
Process Process-19:
Process Process-20:
Process Process-22:
Process Process-21:
Process Process-23:
Process Process-24:
Process Process-25:
Process Process-26:
Process Process-27:
Process Process-29:
Process Process-28:
Process Process-30:
Process Process-31:
Process Process-32:
Process Process-34:
Process Process-35:
Process Process-33:
Process Process-36:
Process Process-37:
Process Process-38:
Process Process-40:
Process Process-39:
Process Process-42:
Process Process-43:
Process Process-41:
Process Process-44:
Process Process-46:
Process Process-47:
Process Process-45:
Process Process-49:
Process Process-48:
Process Process-50:
Process Process-51:
Process Process-53:
Process Process-52:
Process Process-54:
Process Process-56:
Process Process-55:
Process Process-57:
Process Process-58:
Process Process-60:
Process Process-59:
Process Process-61:
Process Process-63:
Process Process-64:
Process Process-62:
Process Process-66:
Process Process-65:
Process Process-68:
Process Process-67:
Process Process-69:
Process Process-70:
Process Process-71:
Process Process-72:
Process Process-74:
Process Process-73:
Process Process-76:
Process Process-77:
Process Process-75:
Process Process-78:
Process Process-79:
Process Process-80:
Process Process-81:
Process Process-82:
Process Process-83:
Process Process-85:
Process Process-86:
Process Process-84:
Process Process-87:
Process Process-88:
Process Process-90:
Process Process-89:
Process Process-92:
Process Process-91:
Process Process-94:
Process Process-93:
Process Process-95:
Process Process-96:
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
Traceback (most recent call last):
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
Traceback (most recent call last):
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
Traceback (most recent call last):
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/apps/python3/3.9.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/python_scripts/cong_loading_fac.py", line 39, in getLoadingFac
    dom_min, dom_max, ncells = getdomain(infile)
  File "/g/data/jh2/av5889/quokka_myrepo/Analysis/functions.py", line 7, in getdomain
    infile = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/jh2/av5889/quokka_myrepo/quokka/sims/N4Gpu/4pcnoAMR-ScalarFix/metal_uniform.in'
